version: '3.9'

services:
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - './redis_data:/data'
